version: "3"
services:
  webapp:
    image: nekoimi/webapp:latest
    ports:
      - 80:80
    environment:
      NGX_WORKER_PROC: 1
      ENV_DEF: API_SERVER_URL TITLE BACKGROUND_IMAGE
      API_SERVER_URL: http://www.example.com
      TITLE: title-name
      BACKGROUND_IMAGE: image-url
    volumes:
      - ./example:/workspace
      - ./deploy.sh:/docker-entrypoint.d/deploy.sh